спускает моки в компоненты и связывает страницы
htmlacademy-react/51735-what-to-watch-9 pull request #5
Opened 2022-03-03 15:12 UTC by TamaraLavrina

2022-03-03 20:37 UTC, Finnko requested changes

2022-03-03 20:37 UTC, Finnko commented on project/src/components/film-buttons/film-buttons.tsx
> +function FilmButtons({currentFilm}:FilmButtonsProps):JSX.Element {
Вроде верстка не пострадает если ты баттон на Link заменишь. Если поедет то твой вариант подойдет только на страницу плеера надо переходить вместе с айди. Чтобы знать какой фильм запускать

2022-03-03 20:37 UTC, Finnko commented on project/src/components/film-buttons/film-buttons.tsx
> +function FilmButtons({currentFilm}:FilmButtonsProps):JSX.Element {
Вот так, или prettier заставлю поставить)
```suggestion
function FilmButtons({currentFilm}: FilmButtonsProps): JSX.Element {
```

2022-03-03 20:37 UTC, Finnko commented on project/src/components/film-card-promo/film-card-promo.tsx
> +          <FilmButtons currentFilm={Promofilm} />
Почему с большой буквы?
```suggestion
          <FilmButtons currentFilm={promofilm} />
```

2022-03-03 20:37 UTC, Finnko commented on project/src/pages/add-review.tsx
> +              />
Ну такое писать разметку звездочки 10 раз. Давай вынесем отдельно, а дальше Array.from({ length: 10 }) и мапишь

2022-03-03 20:37 UTC, Finnko commented on project/src/pages/add-review.tsx
> +    return <NotFound />;
<Navigate to="......" />

2022-03-03 20:37 UTC, Finnko commented on project/src/pages/add-review.tsx
> +  const params = useParams();
```suggestion
  const { id } = useParams<{ id: string }>();
```

2022-03-03 20:37 UTC, Finnko commented on project/src/pages/add-review.tsx
> +  const [userComment, setUserComment] = useState('');
Я за краткость
```suggestion
  const [сomment, setComment] = useState('');
```

2022-03-03 20:37 UTC, Finnko commented on project/src/pages/add-review.tsx
> +  // const [userReviewRating, setUserReviewRating] = useState<number>(rating);
Хуки объявляются возле друг друга в начале компонента

2022-03-03 20:37 UTC, Finnko commented on project/src/pages/movie.tsx
> +  }
Аналогично add review страничке

2022-03-03 20:37 UTC, Finnko commented on project/src/pages/movie.tsx
>    const [activeFilmId, setActiveFilmId] = useState<number | null>(null);
Это должно быть в списке фильмов а не для отдельной страницы

2022-03-05 13:40 UTC, TamaraLavrina commented on project/src/pages/movie.tsx
>    const [activeFilmId, setActiveFilmId] = useState<number | null>(null);
ну я же на 86 строке передаю в SmallFilmCard  это

2022-03-06 09:15 UTC, merged